###############################################################################
# 02_preprocessing.R
# ---------------------------------------------------------------------------
# Purpose:
#   Preprocess raw TCGA-LIHC HTSeq count data and clinical annotations into
#   analysis-ready inputs for DESeq2 differential expression analysis.
#
#   IMPORTANT — single expression modality:
#   This pipeline uses HTSeq-Counts as the sole primary expression matrix.
#   After DESeq2 (script 03), the rlog-transformed matrix serves as the
#   normalized expression input for all downstream analyses:
#     - Machine learning: LASSO (05) and Random Forest (06)
#     - Survival modeling (07) and GEO validation (08)
#     - Hub gene integration (09)
#   No FPKM, TPM, or cross-normalization step is needed — DESeq2's rlog
#   properly accounts for library size, composition, and mean-variance
#   dependency in a single coherent framework.
#
# Key steps:
#   1. Load raw HTSeq count matrix from data/raw/
#   2. Annotate sample types (tumor vs. normal) from TCGA barcodes
#   3. Filter lowly-expressed genes using edgeR::filterByExpr
#      — removes genes with insufficient counts for statistical testing,
#        reducing the multiple-testing burden in DESeq2
#   4. Clinical data cleaning:
#      - Derive overall survival (OS) time and event indicator
#      - Collapse AJCC stage substages for stratified analysis
#      - Filter patients with complete survival records
#   5. Align expression and clinical samples by patient ID
#   6. Exploratory PCA on log2(CPM) to verify tumor/normal separation
#      (final PCA for publication is generated from DESeq2 rlog in 03)
#
# Output:
#   data/processed/counts_filtered.rds   — filtered integer counts → DESeq2
#   data/processed/clinical_clean.rds    — cleaned clinical annotations
#   data/processed/metadata.rds          — sample-level metadata (tissue, etc.)
#
# Note:
#   The normalized expression matrix for ML (formerly log2(FPKM+1)) is now
#   the DESeq2 rlog matrix saved by 03_DESeq2.R as:
#     results/DEG/rlog_normalized.rds
#   All downstream scripts (05–09) load from that path.
#
# Dependencies: SummarizedExperiment, dplyr, edgeR, ggplot2
###############################################################################

# ---- 0. Environment ----
library(SummarizedExperiment)
library(dplyr)
library(tibble)
library(edgeR)      # filterByExpr for count-based low-expression filtering
library(stringr)    # str_detect for stage collapsing
library(ggplot2)

set.seed(2024)
dir.create("../data/processed", recursive = TRUE, showWarnings = FALSE)

# ---- 1. Load raw data ----
# STAR unstranded counts are loaded — no FPKM. The counts are the primary matrix;
# normalized expression for ML will be generated by DESeq2 rlog in 03_DESeq2.R.

counts_se <- readRDS("../data/raw/TCGA_LIHC_counts.rds")
clinical  <- readRDS("../data/raw/TCGA_LIHC_clinical.rds")

# Extract count matrix — use "unstranded" (standard RNA-seq counting)
# Available assays: unstranded, stranded_first, stranded_second,
#   tpm_unstrand, fpkm_unstrand, fpkm_uq_unstrand
count_mat <- assay(counts_se, "unstranded")

# Extract sample metadata from the SummarizedExperiment colData
sample_info <- as.data.frame(colData(counts_se))

message("Raw HTSeq count dimensions: ", paste(dim(count_mat), collapse = " × "))
message("Sample metadata columns: ", ncol(sample_info))

# ---- 2. Sample type annotation ----
# Identify tumor vs. normal samples from the TCGA barcode.
# TCGA barcode structure: TCGA-XX-XXXX-XXX-XXX-XXXX-XX-XXXX-XX
#   Characters 14–15 encode sample type:
#     "01" = Primary Solid Tumor
#     "11" = Solid Tissue Normal
#   Characters 1–12 encode the patient/submitter ID

sample_info <- sample_info %>%
  mutate(
    sample_type_code = substr(barcode, 14, 15),
    tissue = case_when(
      sample_type_code == "01" ~ "Tumor",
      sample_type_code == "11" ~ "Normal",
      TRUE                     ~ "Other"
    ),
    patient_id = substr(barcode, 1, 12)
  )

tumor_samples  <- sample_info %>% filter(tissue == "Tumor")  %>% pull(barcode)
normal_samples <- sample_info %>% filter(tissue == "Normal") %>% pull(barcode)

message("Samples — Tumor: ", length(tumor_samples),
        " | Normal: ", length(normal_samples),
        " | Other: ", sum(sample_info$tissue == "Other"))

# ---- 3. Low-expression gene filtering ----
# Remove genes with very low counts across the majority of samples.
# edgeR::filterByExpr keeps genes with sufficient counts for reliable
# statistical inference. This reduces the multiple-testing burden and
# improves power in DESeq2.
#
# Criteria (defaults from filterByExpr):
#   - min.count:  minimum count in at least N samples (N = smallest group size)
#   - min.total.count: minimum total count across all samples
#   - The function automatically accounts for library size differences.

dge <- DGEList(counts = count_mat)

# The group argument lets filterByExpr require adequate expression in at least
# one condition group (tumor or normal), preventing loss of tissue-specific genes
keep_genes <- filterByExpr(
  dge,
  group       = sample_info$tissue,
  min.count   = 10,
  min.total.count = 15
)

count_mat_filt <- count_mat[keep_genes, ]

message("Genes retained after filtering: ", sum(keep_genes),
        " / ", length(keep_genes),
        " (", round(sum(keep_genes) / length(keep_genes) * 100, 1), "%)")

# ---- 4. Exploratory PCA (log2 CPM) ----
# Quick tumor-vs-normal check using log2(CPM). This is for diagnostic purposes
# only — the publication PCA is generated from DESeq2 rlog in 03_DESeq2.R,
# which properly accounts for the mean-variance relationship.

cpm_log2 <- log2(cpm(dge) + 1)
cpm_filt <- cpm_log2[keep_genes, ]

pca_res <- prcomp(t(cpm_filt), center = TRUE, scale. = TRUE)
pca_df  <- data.frame(
  PC1    = pca_res$x[, 1],
  PC2    = pca_res$x[, 2],
  tissue = sample_info$tissue
)

var_pc1 <- round(summary(pca_res)$importance[2, 1] * 100, 1)
var_pc2 <- round(summary(pca_res)$importance[2, 2] * 100, 1)

pca_plot <- ggplot(pca_df, aes(x = PC1, y = PC2, color = tissue)) +
  geom_point(size = 2, alpha = 0.7) +
  stat_ellipse(level = 0.95) +
  scale_color_manual(values = c(Tumor = "#E41A1C", Normal = "#377EB8")) +
  labs(
    title    = "PCA — TCGA-LIHC (log2 CPM, exploratory)",
    subtitle = paste0("Tumor: ", sum(pca_df$tissue == "Tumor"),
                      " | Normal: ", sum(pca_df$tissue == "Normal")),
    x        = paste0("PC1 (", var_pc1, "%)"),
    y        = paste0("PC2 (", var_pc2, "%)")
  ) +
  theme_minimal(base_size = 13)

ggsave("../figures/PCA_exploratory_log2CPM.pdf", pca_plot, width = 7, height = 6)

# ---- 5. Clinical data cleaning ----
# Derive overall survival (OS) endpoints from TCGA clinical fields.
#
# Vital status coding convention:
#   "Alive" → os_event = 0 (right-censored)
#   "Dead"  → os_event = 1 (event occurred)
#
# OS time:
#   - If dead:     days_to_death
#   - If alive:    days_to_last_follow_up
#   Patients with missing or ≤ 0 OS time are excluded.

clinical_clean <- clinical %>%
  select(
    submitter_id,
    days_to_death,
    days_to_last_follow_up,
    vital_status,
    age_at_diagnosis,
    gender,
    race,
    ajcc_pathologic_stage,
    ajcc_pathologic_t,
    ajcc_pathologic_n,
    ajcc_pathologic_m,
    prior_malignancy,
    icd_10_code,
    tissue_or_organ_of_origin,
    site_of_resection_or_biopsy,
    primary_diagnosis,
    prior_treatment,
    tumor_grade,
    child_pugh_classification,
    ishak_fibrosis_score
  ) %>%
  mutate(
    # Derive OS time
    os_time = if_else(
      vital_status == "Dead",
      days_to_death,
      days_to_last_follow_up
    ),
    # OS event indicator
    os_event = if_else(vital_status == "Dead", 1, 0),

    # Remove implausible survival times
    os_time = if_else(os_time <= 0 | is.na(os_time), NA_real_, os_time),

    # Age at diagnosis in years
    age_years = age_at_diagnosis / 365.25,

    # Clean stage: collapse substages for grouped comparison
    stage_simple = case_when(
      str_detect(ajcc_pathologic_stage, "Stage I")  ~ "I",
      str_detect(ajcc_pathologic_stage, "Stage II") ~ "II",
      str_detect(ajcc_pathologic_stage, "Stage III") ~ "III",
      str_detect(ajcc_pathologic_stage, "Stage IV") ~ "IV",
      TRUE ~ NA_character_
    )
  ) %>%
  # Keep only patients with valid OS data
  filter(!is.na(os_time), os_time > 0)

rownames(clinical_clean) <- clinical_clean$submitter_id

message("Clinical data cleaned: ", nrow(clinical_clean), " patients retained")

# ---- 6. Align expression & clinical samples ----
# Match by patient ID (first 12 characters of TCGA barcode).
# Only samples present in both expression and clinical tables are retained.

patient_ids_expr <- substr(colnames(count_mat_filt), 1, 12)
matched_patients <- intersect(patient_ids_expr, clinical_clean$submitter_id)

match_idx_expr <- which(patient_ids_expr %in% matched_patients)
match_idx_clin <- match(patient_ids_expr[match_idx_expr], clinical_clean$submitter_id)

count_mat_matched   <- count_mat_filt[, match_idx_expr]
clinical_matched    <- clinical_clean[match_idx_clin, ]
sample_info_matched <- sample_info[match_idx_expr, ]

message("Matched samples (expression ∩ clinical): ", length(match_idx_expr))

# Verify alignment
stopifnot(ncol(count_mat_matched) == nrow(clinical_matched))
stopifnot(all(substr(colnames(count_mat_matched), 1, 12) == clinical_matched$submitter_id))

# ---- 7. Save processed data ----
saveRDS(count_mat_matched,   "../data/processed/counts_filtered.rds")
saveRDS(clinical_matched,    "../data/processed/clinical_clean.rds")
saveRDS(sample_info_matched, "../data/processed/metadata.rds")

# ---- 8. Summary ----
cat("\n============================================================\n")
cat(" Preprocessing complete.\n")
cat("\n Input:  HTSeq raw counts (single primary matrix)\n")
cat(" Output files in data/processed/:\n")
cat("   - counts_filtered.rds   (filtered integer counts → DESeq2)\n")
cat("   - clinical_clean.rds    (clinical annotations, matched)\n")
cat("   - metadata.rds          (sample-level metadata)\n")
cat("\n Next step:\n")
cat("   Run 03_DESeq2.R → produces rlog_normalized.rds\n")
cat("   This rlog matrix is the normalized expression input\n")
cat("   for all downstream ML & survival analyses (05–09).\n")
cat("============================================================\n")
